/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.NasabahControl;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class CSLandingPage extends javax.swing.JFrame {

    private NasabahControl nasabahControl;
    
    public CSLandingPage() {
        initComponents();
        jumlahNasabahText.setEditable(false);
        
        // Inisialisasi objek NasabahControl
        nasabahControl = new NasabahControl();
        
        // Memperbarui tampilan jumlah nasabah saat halaman dimuat
        updateJumlahNasabah();
    }
    
    private void updateJumlahNasabah() {
        int jumlahNasabah = nasabahControl.countNasabah();
        jumlahNasabahText.setText(Integer.toString(jumlahNasabah));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        HeaderTitle = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        PagePanel = new javax.swing.JPanel();
        logoCBA = new javax.swing.JLabel();
        jumlahNasabahLabel = new javax.swing.JLabel();
        jumlahNasabahText = new javax.swing.JTextArea();
        optionToDoCS = new javax.swing.JPanel();
        registNasabahPanel = new javax.swing.JPanel();
        regNasabahLabel = new javax.swing.JLabel();
        logoRegNasabah = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        rekeningPanel = new javax.swing.JPanel();
        rekeningLabel = new javax.swing.JLabel();
        logoRekening = new javax.swing.JLabel();
        detailNasabahPanel = new javax.swing.JPanel();
        detailLabel = new javax.swing.JLabel();
        logoDetail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(51, 51, 255));

        HeaderTitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        HeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        HeaderTitle.setText("Customer Service ");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/logo cba.png"))); // NOI18N

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Logo)
                .addGap(18, 18, 18)
                .addComponent(HeaderTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logo)
                    .addComponent(HeaderTitle))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        PagePanel.setBackground(new java.awt.Color(255, 255, 255));

        logoCBA.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logoCBA.setForeground(new java.awt.Color(51, 102, 255));
        logoCBA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/logo besar.png"))); // NOI18N

        jumlahNasabahLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jumlahNasabahLabel.setForeground(new java.awt.Color(51, 102, 255));
        jumlahNasabahLabel.setText("Jumlah Nasabah :");

        jumlahNasabahText.setBackground(new java.awt.Color(255, 255, 255));
        jumlahNasabahText.setColumns(20);
        jumlahNasabahText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jumlahNasabahText.setForeground(new java.awt.Color(51, 51, 255));
        jumlahNasabahText.setRows(5);

        javax.swing.GroupLayout PagePanelLayout = new javax.swing.GroupLayout(PagePanel);
        PagePanel.setLayout(PagePanelLayout);
        PagePanelLayout.setHorizontalGroup(
            PagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PagePanelLayout.createSequentialGroup()
                .addContainerGap(367, Short.MAX_VALUE)
                .addGroup(PagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PagePanelLayout.createSequentialGroup()
                        .addComponent(jumlahNasabahLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlahNasabahText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addComponent(logoCBA))
                .addGap(374, 374, 374))
        );
        PagePanelLayout.setVerticalGroup(
            PagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PagePanelLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(logoCBA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlahNasabahLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahNasabahText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionToDoCS.setBackground(new java.awt.Color(51, 51, 255));

        registNasabahPanel.setBackground(new java.awt.Color(51, 51, 255));
        registNasabahPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registNasabahPanelMouseClicked(evt);
            }
        });

        regNasabahLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regNasabahLabel.setForeground(new java.awt.Color(255, 255, 255));
        regNasabahLabel.setText("Register Nasabah");

        logoRegNasabah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/nasabah regist logo.png"))); // NOI18N

        javax.swing.GroupLayout registNasabahPanelLayout = new javax.swing.GroupLayout(registNasabahPanel);
        registNasabahPanel.setLayout(registNasabahPanelLayout);
        registNasabahPanelLayout.setHorizontalGroup(
            registNasabahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registNasabahPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(logoRegNasabah)
                .addGap(27, 27, 27)
                .addComponent(regNasabahLabel)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        registNasabahPanelLayout.setVerticalGroup(
            registNasabahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registNasabahPanelLayout.createSequentialGroup()
                .addGroup(registNasabahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registNasabahPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(regNasabahLabel))
                    .addGroup(registNasabahPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(logoRegNasabah)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        logoutButton.setBackground(new java.awt.Color(255, 0, 51));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        rekeningPanel.setBackground(new java.awt.Color(51, 51, 255));
        rekeningPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rekeningPanelMouseClicked(evt);
            }
        });

        rekeningLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rekeningLabel.setForeground(new java.awt.Color(255, 255, 255));
        rekeningLabel.setText("Rekening");

        logoRekening.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/rekening logo.png"))); // NOI18N

        javax.swing.GroupLayout rekeningPanelLayout = new javax.swing.GroupLayout(rekeningPanel);
        rekeningPanel.setLayout(rekeningPanelLayout);
        rekeningPanelLayout.setHorizontalGroup(
            rekeningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rekeningPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(logoRekening)
                .addGap(33, 33, 33)
                .addComponent(rekeningLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rekeningPanelLayout.setVerticalGroup(
            rekeningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rekeningPanelLayout.createSequentialGroup()
                .addGroup(rekeningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rekeningPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(rekeningLabel))
                    .addGroup(rekeningPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(logoRekening)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        detailNasabahPanel.setBackground(new java.awt.Color(51, 51, 255));
        detailNasabahPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailNasabahPanelMouseClicked(evt);
            }
        });

        detailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        detailLabel.setForeground(new java.awt.Color(255, 255, 255));
        detailLabel.setText("Detail Nasabah");

        logoDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/detail logo.png"))); // NOI18N

        javax.swing.GroupLayout detailNasabahPanelLayout = new javax.swing.GroupLayout(detailNasabahPanel);
        detailNasabahPanel.setLayout(detailNasabahPanelLayout);
        detailNasabahPanelLayout.setHorizontalGroup(
            detailNasabahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailNasabahPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(logoDetail)
                .addGap(34, 34, 34)
                .addComponent(detailLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detailNasabahPanelLayout.setVerticalGroup(
            detailNasabahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailNasabahPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(detailLabel)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailNasabahPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoDetail)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout optionToDoCSLayout = new javax.swing.GroupLayout(optionToDoCS);
        optionToDoCS.setLayout(optionToDoCSLayout);
        optionToDoCSLayout.setHorizontalGroup(
            optionToDoCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionToDoCSLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(logoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(optionToDoCSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionToDoCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registNasabahPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rekeningPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailNasabahPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        optionToDoCSLayout.setVerticalGroup(
            optionToDoCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionToDoCSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registNasabahPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rekeningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailNasabahPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(optionToDoCS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optionToDoCS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Apakah Anda ingin LOGOUT?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        
        if (response == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Berhasil LOGOUT!");
            LoginPage l = new LoginPage();
            CSLandingPage cs = new CSLandingPage();
            
            l.setVisible(true);
            cs.setVisible(false);
            dispose();
        } else if (response == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Batal LOGOUT!");
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void registNasabahPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registNasabahPanelMouseClicked
        registerNasabahPage rn = new registerNasabahPage();
        CSLandingPage cs = new CSLandingPage();
        
        rn.setVisible(true);
        cs.setVisible(false);
        dispose();
    }//GEN-LAST:event_registNasabahPanelMouseClicked

    private void rekeningPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rekeningPanelMouseClicked
        rekeningPage re = new rekeningPage();
        CSLandingPage cs = new CSLandingPage();
        
        re.setVisible(true);
        cs.setVisible(false);
        dispose();
    }//GEN-LAST:event_rekeningPanelMouseClicked

    private void detailNasabahPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailNasabahPanelMouseClicked
        detailNasabahPage d = new detailNasabahPage();
        CSLandingPage cs = new CSLandingPage();
        
        d.setVisible(true);
        cs.setVisible(false);
    }//GEN-LAST:event_detailNasabahPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CSLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CSLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CSLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CSLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CSLandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel HeaderTitle;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PagePanel;
    private javax.swing.JLabel detailLabel;
    private javax.swing.JPanel detailNasabahPanel;
    private javax.swing.JLabel jumlahNasabahLabel;
    private javax.swing.JTextArea jumlahNasabahText;
    private javax.swing.JLabel logoCBA;
    private javax.swing.JLabel logoDetail;
    private javax.swing.JLabel logoRegNasabah;
    private javax.swing.JLabel logoRekening;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel optionToDoCS;
    private javax.swing.JLabel regNasabahLabel;
    private javax.swing.JPanel registNasabahPanel;
    private javax.swing.JLabel rekeningLabel;
    private javax.swing.JPanel rekeningPanel;
    // End of variables declaration//GEN-END:variables
}
