package view;

import control.NasabahControl;
import control.RekeningControl;
import static java.nio.file.Files.list;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import static java.util.Collections.list;
import java.util.Date;
import java.util.List;
import java.util.Random;
import static javax.management.Query.value;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Nasabah;
import model.Rekening;
import table.TableRekening;

public class detailNasabahPage extends javax.swing.JFrame {

    NasabahControl nControl = new NasabahControl();
    RekeningControl rControl = new RekeningControl();
    
    List<Rekening> listRekening;
    TableRekening tableRekening = new TableRekening(listRekening);
    
    public detailNasabahPage() {
        initComponents();
        setComponent(false);
        clearText();
    }
    
    public void setComponent(boolean value){
        cinJtext.setEditable(value);
        namaJtext.setEditable(value);
        nikJtext.setEditable(value);
        tanggalLahirJtext.setEditable(value);
        alamatJtext.setEditable(value);
        pekerjaanJtext.setEditable(value);
    }
    
    public void clearText(){
        cinJtext.setText("");
        namaJtext.setText("");
        nikJtext.setText("");
        tanggalLahirJtext.setText("");
        alamatJtext.setText("");
        pekerjaanJtext.setText("");
    }
    
    private void showData() {
        DefaultTableModel model = (DefaultTableModel) rekeningTable.getModel();
        model.setRowCount(0); // Menghapus semua baris yang ada pada tabel

        Nasabah n = nControl.showNasabahby(findJtext.getText());
        if (n != null) {
            TableRekening tableRekening = rControl.getRekeningTableByNasabah(n);
            List<Rekening> rekeningList = tableRekening.getList(); // Menggunakan getList() untuk mendapatkan daftar rekening

            for (Rekening rekening : rekeningList) {
                Object[] row = new Object[3];
                row[0] = rekening.getNoRekening();
                row[1] = rekening.getJenis();
                row[2] = rekening.getSaldo();
                model.addRow(row);
            }
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameJtext = new javax.swing.JTextArea();
        Header = new javax.swing.JPanel();
        HeaderTitle = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        optionToDoCS = new javax.swing.JPanel();
        registNasabahPanel = new javax.swing.JPanel();
        regNasabahLabel = new javax.swing.JLabel();
        logoRegNasabah = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        rekeningPanel = new javax.swing.JPanel();
        rekeningLabel = new javax.swing.JLabel();
        logoRekening = new javax.swing.JLabel();
        detailNasabahPanel = new javax.swing.JPanel();
        detailLabel = new javax.swing.JLabel();
        logoDetail = new javax.swing.JLabel();
        detailPanel = new javax.swing.JPanel();
        mainPanelTitle = new javax.swing.JLabel();
        cinJtext = new javax.swing.JTextArea();
        namaLabel = new javax.swing.JLabel();
        nikLabel = new javax.swing.JLabel();
        namaJtext = new javax.swing.JTextArea();
        pekerjaanJtext = new javax.swing.JTextArea();
        tanggalLahirLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        tanggalLahirJtext = new javax.swing.JTextArea();
        pekerjaanLabel = new javax.swing.JLabel();
        alamatJtext = new javax.swing.JTextArea();
        nikJtext = new javax.swing.JTextArea();
        cinLabel = new javax.swing.JLabel();
        findJtext = new javax.swing.JTextArea();
        searchButton = new javax.swing.JButton();
        listRekeningLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rekeningTable = new javax.swing.JTable();
        lainButton = new javax.swing.JButton();

        usernameJtext.setColumns(20);
        usernameJtext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameJtext.setForeground(new java.awt.Color(0, 0, 0));
        usernameJtext.setRows(5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(51, 51, 255));

        HeaderTitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        HeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        HeaderTitle.setText("Customer Service ");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/logo cba.png"))); // NOI18N

        BackButton.setBackground(new java.awt.Color(153, 153, 153));
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Logo)
                .addGap(18, 18, 18)
                .addComponent(HeaderTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(89, 89, 89))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logo)
                    .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HeaderTitle)
                        .addComponent(BackButton)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        optionToDoCS.setBackground(new java.awt.Color(51, 51, 255));

        registNasabahPanel.setBackground(new java.awt.Color(51, 51, 255));
        registNasabahPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registNasabahPanelMouseClicked(evt);
            }
        });

        regNasabahLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regNasabahLabel.setForeground(new java.awt.Color(255, 255, 255));
        regNasabahLabel.setText("Register Nasabah");

        logoRegNasabah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/nasabah regist logo.png"))); // NOI18N

        javax.swing.GroupLayout registNasabahPanelLayout = new javax.swing.GroupLayout(registNasabahPanel);
        registNasabahPanel.setLayout(registNasabahPanelLayout);
        registNasabahPanelLayout.setHorizontalGroup(
            registNasabahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registNasabahPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(logoRegNasabah)
                .addGap(27, 27, 27)
                .addComponent(regNasabahLabel)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        registNasabahPanelLayout.setVerticalGroup(
            registNasabahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registNasabahPanelLayout.createSequentialGroup()
                .addGroup(registNasabahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registNasabahPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(regNasabahLabel))
                    .addGroup(registNasabahPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(logoRegNasabah)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        logoutButton.setBackground(new java.awt.Color(255, 0, 51));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        rekeningPanel.setBackground(new java.awt.Color(51, 51, 255));
        rekeningPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rekeningPanelMouseClicked(evt);
            }
        });

        rekeningLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rekeningLabel.setForeground(new java.awt.Color(255, 255, 255));
        rekeningLabel.setText("Rekening");

        logoRekening.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/rekening logo.png"))); // NOI18N

        javax.swing.GroupLayout rekeningPanelLayout = new javax.swing.GroupLayout(rekeningPanel);
        rekeningPanel.setLayout(rekeningPanelLayout);
        rekeningPanelLayout.setHorizontalGroup(
            rekeningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rekeningPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(logoRekening)
                .addGap(33, 33, 33)
                .addComponent(rekeningLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rekeningPanelLayout.setVerticalGroup(
            rekeningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rekeningPanelLayout.createSequentialGroup()
                .addGroup(rekeningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rekeningPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(rekeningLabel))
                    .addGroup(rekeningPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(logoRekening)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        detailNasabahPanel.setBackground(new java.awt.Color(153, 153, 153));
        detailNasabahPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailNasabahPanelMouseClicked(evt);
            }
        });

        detailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        detailLabel.setForeground(new java.awt.Color(255, 255, 255));
        detailLabel.setText("Detail Nasabah");

        logoDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/detail logo.png"))); // NOI18N

        javax.swing.GroupLayout detailNasabahPanelLayout = new javax.swing.GroupLayout(detailNasabahPanel);
        detailNasabahPanel.setLayout(detailNasabahPanelLayout);
        detailNasabahPanelLayout.setHorizontalGroup(
            detailNasabahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailNasabahPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(logoDetail)
                .addGap(34, 34, 34)
                .addComponent(detailLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detailNasabahPanelLayout.setVerticalGroup(
            detailNasabahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailNasabahPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(detailLabel)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailNasabahPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoDetail)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout optionToDoCSLayout = new javax.swing.GroupLayout(optionToDoCS);
        optionToDoCS.setLayout(optionToDoCSLayout);
        optionToDoCSLayout.setHorizontalGroup(
            optionToDoCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionToDoCSLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(logoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(optionToDoCSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionToDoCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registNasabahPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rekeningPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailNasabahPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        optionToDoCSLayout.setVerticalGroup(
            optionToDoCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionToDoCSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registNasabahPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rekeningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailNasabahPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(27, 27, 27))
        );

        detailPanel.setBackground(new java.awt.Color(255, 255, 255));

        mainPanelTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mainPanelTitle.setForeground(new java.awt.Color(51, 51, 255));
        mainPanelTitle.setText("DETAIL NASABAH");

        cinJtext.setColumns(20);
        cinJtext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cinJtext.setForeground(new java.awt.Color(0, 0, 0));
        cinJtext.setRows(5);

        namaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(51, 51, 255));
        namaLabel.setText("Nama");

        nikLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nikLabel.setForeground(new java.awt.Color(51, 51, 255));
        nikLabel.setText("NIK");

        namaJtext.setColumns(20);
        namaJtext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        namaJtext.setForeground(new java.awt.Color(0, 0, 0));
        namaJtext.setRows(5);

        pekerjaanJtext.setColumns(20);
        pekerjaanJtext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pekerjaanJtext.setForeground(new java.awt.Color(0, 0, 0));
        pekerjaanJtext.setRows(5);

        tanggalLahirLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tanggalLahirLabel.setForeground(new java.awt.Color(51, 51, 255));
        tanggalLahirLabel.setText("Tanggal Lahir");

        alamatLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        alamatLabel.setForeground(new java.awt.Color(51, 51, 255));
        alamatLabel.setText("Alamat");

        tanggalLahirJtext.setColumns(20);
        tanggalLahirJtext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tanggalLahirJtext.setForeground(new java.awt.Color(0, 0, 0));
        tanggalLahirJtext.setRows(5);

        pekerjaanLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pekerjaanLabel.setForeground(new java.awt.Color(51, 51, 255));
        pekerjaanLabel.setText("Pekerjaan");

        alamatJtext.setColumns(20);
        alamatJtext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alamatJtext.setForeground(new java.awt.Color(0, 0, 0));
        alamatJtext.setRows(5);

        nikJtext.setColumns(20);
        nikJtext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nikJtext.setForeground(new java.awt.Color(0, 0, 0));
        nikJtext.setRows(5);

        cinLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cinLabel.setForeground(new java.awt.Color(51, 51, 255));
        cinLabel.setText("CIN");

        findJtext.setBackground(new java.awt.Color(204, 204, 204));
        findJtext.setColumns(20);
        findJtext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        findJtext.setRows(5);

        searchButton.setBackground(new java.awt.Color(51, 102, 255));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        listRekeningLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listRekeningLabel.setForeground(new java.awt.Color(51, 51, 255));
        listRekeningLabel.setText("LIST REKENING");

        rekeningTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nomor Rekening", "Jenis", "Saldo"
            }
        ));
        jScrollPane1.setViewportView(rekeningTable);

        lainButton.setBackground(new java.awt.Color(204, 204, 0));
        lainButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lainButton.setForeground(new java.awt.Color(255, 255, 255));
        lainButton.setText("Nasabah Lain");
        lainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lainButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailPanelLayout = new javax.swing.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailPanelLayout.createSequentialGroup()
                                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cinJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tanggalLahirJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tanggalLahirLabel)
                                    .addComponent(cinLabel))
                                .addGap(18, 18, 18)
                                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(detailPanelLayout.createSequentialGroup()
                                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(alamatJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(alamatLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pekerjaanLabel)
                                            .addComponent(pekerjaanJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(detailPanelLayout.createSequentialGroup()
                                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(namaJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(namaLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nikLabel)
                                            .addComponent(nikJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(detailPanelLayout.createSequentialGroup()
                                .addGap(368, 368, 368)
                                .addComponent(listRekeningLabel))
                            .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailPanelLayout.createSequentialGroup()
                                    .addGap(138, 138, 138)
                                    .addComponent(findJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lainButton))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(mainPanelTitle)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(mainPanelTitle)
                .addGap(49, 49, 49)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(nikLabel)
                    .addComponent(cinLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cinJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nikJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamatLabel)
                    .addComponent(pekerjaanLabel)
                    .addComponent(tanggalLahirLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggalLahirJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamatJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pekerjaanJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(listRekeningLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(optionToDoCS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionToDoCS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registNasabahPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registNasabahPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registNasabahPanelMouseClicked

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void rekeningPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rekeningPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rekeningPanelMouseClicked

    private void detailNasabahPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailNasabahPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_detailNasabahPanelMouseClicked

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed

        CSLandingPage cs = new CSLandingPage();
        detailNasabahPage d = new detailNasabahPage();

        cs.setVisible(true);
        d.setVisible(false);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try {
            Nasabah n = nControl.showNasabahby(findJtext.getText());
            if (n == null) {
                clearText();
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            } else {
                cinJtext.setText(n.getCustomer_identification());
                namaJtext.setText(n.getNama());
                nikJtext.setText(n.getNik());
                tanggalLahirJtext.setText(n.getTanggalLahir());
                alamatJtext.setText(n.getAlamat());
                pekerjaanJtext.setText(n.getPekerjaan());

                showData(); // Memanggil metode showData() untuk menampilkan data rekening
            }
        } catch (Exception e) {
            System.out.println("Error:  "+e.getMessage());
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void lainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lainButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lainButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detailNasabahPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detailNasabahPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detailNasabahPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detailNasabahPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detailNasabahPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel HeaderTitle;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextArea alamatJtext;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextArea cinJtext;
    private javax.swing.JLabel cinLabel;
    private javax.swing.JLabel detailLabel;
    private javax.swing.JPanel detailNasabahPanel;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JTextArea findJtext;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lainButton;
    private javax.swing.JLabel listRekeningLabel;
    private javax.swing.JLabel logoDetail;
    private javax.swing.JLabel logoRegNasabah;
    private javax.swing.JLabel logoRekening;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel mainPanelTitle;
    private javax.swing.JTextArea namaJtext;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextArea nikJtext;
    private javax.swing.JLabel nikLabel;
    private javax.swing.JPanel optionToDoCS;
    private javax.swing.JTextArea pekerjaanJtext;
    private javax.swing.JLabel pekerjaanLabel;
    private javax.swing.JLabel regNasabahLabel;
    private javax.swing.JPanel registNasabahPanel;
    private javax.swing.JLabel rekeningLabel;
    private javax.swing.JPanel rekeningPanel;
    private javax.swing.JTable rekeningTable;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextArea tanggalLahirJtext;
    private javax.swing.JLabel tanggalLahirLabel;
    private javax.swing.JTextArea usernameJtext;
    // End of variables declaration//GEN-END:variables
}
