/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.Back_OfficeControl;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import model.Back_Office;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JTextField;

import exception.PasswordException;
import exception.UsernameException;
import exception.InvalidInputanKosongException;

public class ManajerBOPage extends javax.swing.JFrame {
    
    private Back_OfficeControl boControl;
    
    List<Back_Office> listBO;
    String action = null;
    
    
    public ManajerBOPage() {
        boControl = new Back_OfficeControl();
        
        initComponents();
        setComponent(false);
        clearText();
        
        updateButton.setEnabled(false);
        firedButton.setEnabled(false);
        
        showData();
    }
    
    public static boolean isPasswordValid(String password) {
        String regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@#$%^&+=]).{8,16}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(password);
        return matcher.matches();
    }
    
//    public void usernameException() throws UsernameException{
//        if(!isUsernameValid(usernameJtext.getText())){
//            throw new UsernameException();
//        }
//    }
    
//    public void passwordException() throws PasswordException{
//        if(!isPasswordValid(passwordJtext.getText())){
//            throw new PasswordException();
//        }
//    }
    
    public void setComponent(boolean value){
        idJtext.setEnabled(value);
        namaJtext.setEnabled(value);
        usernameJtext.setEnabled(value);
        passwordJtext.setEnabled(value);
        jDateChooser.setEnabled(value);
        gajiJtext.setEnabled(value);
    }
    
    public void clearText(){
        idJtext.setText("");
        namaJtext.setText("");
        usernameJtext.setText("");
        passwordJtext.setText("");
        jDateChooser.setDate(null);
        jDateChooser.setToolTipText("");
        gajiJtext.setText("");
    }

    
    public void setDefaultID(){
        String AutoID = boControl.AutoID();
        idJtext.setText(AutoID);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        HeaderTitle = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ManagerBOPanel = new javax.swing.JPanel();
        findJtext = new javax.swing.JTextArea();
        searchButton = new javax.swing.JButton();
        pageLabel = new javax.swing.JLabel();
        usernameJtext = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBO = new javax.swing.JTable();
        labelNama = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        namaJtext = new javax.swing.JTextArea();
        passwordLabel = new javax.swing.JLabel();
        passwordJtext = new javax.swing.JTextArea();
        tanggalLahirLabel = new javax.swing.JLabel();
        gajiJtext = new javax.swing.JTextArea();
        gajiLabel = new javax.swing.JLabel();
        recruitButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        firedButton = new javax.swing.JButton();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        idJtext = new javax.swing.JTextArea();
        labelID = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(51, 51, 255));

        HeaderTitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        HeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        HeaderTitle.setText("Manager Page");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/logo cba.png"))); // NOI18N

        logoutButton.setBackground(new java.awt.Color(153, 153, 153));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Back");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Logo)
                .addGap(18, 18, 18)
                .addComponent(HeaderTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(81, 81, 81))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logo)
                    .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HeaderTitle)
                        .addComponent(logoutButton)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        ManagerBOPanel.setBackground(new java.awt.Color(255, 255, 255));

        findJtext.setBackground(new java.awt.Color(204, 204, 204));
        findJtext.setColumns(20);
        findJtext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        findJtext.setRows(5);

        searchButton.setBackground(new java.awt.Color(51, 102, 255));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        pageLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pageLabel.setForeground(new java.awt.Color(51, 102, 255));
        pageLabel.setText("Back Office Management");

        usernameJtext.setColumns(20);
        usernameJtext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameJtext.setRows(5);

        jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));

        tableBO.setBackground(new java.awt.Color(204, 204, 204));
        tableBO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "bo_id", "username", "nama", "tanggal_lahir", "gaji"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableBO);

        labelNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNama.setText("Nama");

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameLabel.setText("Password");

        namaJtext.setColumns(20);
        namaJtext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        namaJtext.setRows(5);

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel.setText("Password");

        passwordJtext.setColumns(20);
        passwordJtext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordJtext.setRows(5);

        tanggalLahirLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tanggalLahirLabel.setText("Tanggal Lahir");

        gajiJtext.setColumns(20);
        gajiJtext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gajiJtext.setRows(5);

        gajiLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gajiLabel.setText("Gaji");

        recruitButton.setBackground(new java.awt.Color(51, 102, 255));
        recruitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        recruitButton.setForeground(new java.awt.Color(255, 255, 255));
        recruitButton.setText("RECRUIT");
        recruitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recruitButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(255, 255, 255));
        updateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(51, 102, 255));
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        firedButton.setBackground(new java.awt.Color(255, 0, 51));
        firedButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firedButton.setForeground(new java.awt.Color(255, 255, 255));
        firedButton.setText("FIRED");
        firedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firedButtonActionPerformed(evt);
            }
        });

        jDateChooser.setDateFormatString("yyyy-MM-dd\n");

        idJtext.setColumns(20);
        idJtext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idJtext.setRows(5);

        labelID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelID.setText("ID");

        saveButton.setBackground(new java.awt.Color(255, 255, 255));
        saveButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveButton.setForeground(new java.awt.Color(51, 204, 0));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancleButton.setBackground(new java.awt.Color(255, 255, 255));
        cancleButton.setForeground(new java.awt.Color(204, 0, 0));
        cancleButton.setText("Cancel");
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManagerBOPanelLayout = new javax.swing.GroupLayout(ManagerBOPanel);
        ManagerBOPanel.setLayout(ManagerBOPanelLayout);
        ManagerBOPanelLayout.setHorizontalGroup(
            ManagerBOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagerBOPanelLayout.createSequentialGroup()
                .addGroup(ManagerBOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagerBOPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(ManagerBOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ManagerBOPanelLayout.createSequentialGroup()
                                .addGroup(ManagerBOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pageLabel)
                                    .addComponent(labelNama)
                                    .addComponent(usernameLabel)
                                    .addComponent(passwordLabel)
                                    .addComponent(tanggalLahirLabel)
                                    .addComponent(gajiLabel)
                                    .addComponent(idJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelID))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagerBOPanelLayout.createSequentialGroup()
                                .addGroup(ManagerBOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(ManagerBOPanelLayout.createSequentialGroup()
                                        .addGroup(ManagerBOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(gajiJtext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                            .addComponent(passwordJtext, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(usernameJtext, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(ManagerBOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firedButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(updateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(ManagerBOPanelLayout.createSequentialGroup()
                                        .addComponent(namaJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(recruitButton)))
                                .addGap(94, 94, 94))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagerBOPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancleButton)
                        .addGap(84, 84, 84)))
                .addGroup(ManagerBOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ManagerBOPanelLayout.createSequentialGroup()
                        .addComponent(findJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        ManagerBOPanelLayout.setVerticalGroup(
            ManagerBOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerBOPanelLayout.createSequentialGroup()
                .addGroup(ManagerBOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagerBOPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(pageLabel)
                        .addGap(23, 23, 23)
                        .addComponent(labelID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ManagerBOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recruitButton))
                        .addGap(18, 18, 18)
                        .addComponent(usernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ManagerBOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firedButton))
                        .addGap(18, 18, 18)
                        .addComponent(passwordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ManagerBOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateButton))
                        .addGap(18, 18, 18)
                        .addComponent(tanggalLahirLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gajiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gajiJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ManagerBOPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ManagerBOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ManagerBOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(saveButton)
                                .addComponent(cancleButton))
                            .addGroup(ManagerBOPanelLayout.createSequentialGroup()
                                .addGroup(ManagerBOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(findJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(ManagerBOPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed

            ManajerBOPage c = new ManajerBOPage();
            ManajerLandingPage m = new ManajerLandingPage();

            c.setVisible(false);
            m.setVisible(true);
            dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void firedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firedButtonActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ignin memberhentikan Karyawan?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if(getAnswer == JOptionPane.YES_OPTION){
            try{
                boControl.deleteDataBO(idJtext.getText());
                clearText();
                showData();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            }catch(Exception e){
                System.out.println("Error:  "+e.getMessage());
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Data tidak jadi dihapus");
        }
    }//GEN-LAST:event_firedButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        setComponent(true);
        idJtext.setEditable(false);
        action = "Update";
    }//GEN-LAST:event_updateButtonActionPerformed

    private void recruitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recruitButtonActionPerformed
        setComponent(true);
        clearText();
        setDefaultID();
        idJtext.setEditable(false);
        action = "Recruit";
    }//GEN-LAST:event_recruitButtonActionPerformed
    
    public void setEditDeleteBtn(boolean value){
        updateButton.setEnabled(value);
        firedButton.setEnabled(value);
    }
    
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        setEditDeleteBtn(true);
        
        try{
            Back_Office bo = boControl.showBOby(findJtext.getText());
            if(bo == null){
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else{
                idJtext.setText(bo.getBo_id());
                namaJtext.setText(bo.getNama());
                usernameJtext.setText(bo.getUsername());
                passwordJtext.setText(bo.getPassword());
                String gaji = String.valueOf(bo.getGaji());
                gajiJtext.setText(gaji);
                
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                jDateChooser.setDateFormatString("yyyy-MM-dd");
                Date tanggalLahir = dateFormat.parse(bo.getTanggalLahir());
                jDateChooser.setDate(tanggalLahir);
            }
        }catch(Exception e){
            System.out.println("Error:  "+e.getMessage());
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        int i = 0;
        try {

            String gajiStr = gajiJtext.getText().trim();
            double gaji = Double.parseDouble(gajiStr);
            String tanggalLahir = ((JTextField) jDateChooser.getDateEditor().getUiComponent()).getText();
            Back_Office bo = new Back_Office(idJtext.getText(), usernameJtext.getText(), passwordJtext.getText(), namaJtext.getText(), tanggalLahir, gaji);

            if (action.equals("Recruit")) {
                boControl.insertDataBO(bo);
            } else {
                boControl.updateDataBO(bo, idJtext.getText());
            }

            JOptionPane.showMessageDialog(ManagerBOPanel, "Data Berhasil Disimpan");
            i = 1;
        } catch (Exception e) {
            
        }

        if (i == 1) {
            clearText();
            showData();
            setComponent(false);
            setEditDeleteBtn(false);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_cancleButtonActionPerformed
    
    public void showData(){
        tableBO.setModel((TableModel) boControl.showBO(""));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManajerBOPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManajerBOPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManajerBOPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManajerBOPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManajerBOPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel HeaderTitle;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel ManagerBOPanel;
    private javax.swing.JButton cancleButton;
    private javax.swing.JTextArea findJtext;
    private javax.swing.JButton firedButton;
    private javax.swing.JTextArea gajiJtext;
    private javax.swing.JLabel gajiLabel;
    private javax.swing.JTextArea idJtext;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNama;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextArea namaJtext;
    private javax.swing.JLabel pageLabel;
    private javax.swing.JTextArea passwordJtext;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton recruitButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTable tableBO;
    private javax.swing.JLabel tanggalLahirLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextArea usernameJtext;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
